### ISSUE TITLE
LenAuth на Moodle 3

### ISSUE THREAD

**Issue by dichenko** [tigusigalpa/moodle-auth_lenauth#10]
Плагин не работает на третьей версии moodle
https://www.dropbox.com/s/2d78710w4hsv74q/moodle.PNG?dl=0&preview=moodle.PNG

Допилите, пожалуйста!

**Comment by tigusigalpa** [comment]
добрый день, посмотрел скрин и не понял при чем тут LenAuth, там 3 других плагина

**Comment by dichenko** [comment]
Спасибо за быстрый ответ!
Эти ошибки в плагинах появились сразу после установки LenAuth, при этом moodle не пропускает дальше в админку. 
Это может быть связано с LenAuth?

**Comment by tigusigalpa** [comment]
очень странно, эти плагины никак с LenAuth не связаны, проверить можно лишь таким способом
в БД в таблице mdl_config в поле debugdisplay поставьте 1 и тогда он покажет ошибки кода

**Comment by dichenko** [comment]
Восстановил сайт из бекапа, начал эксперименты заново.
Если ставить LenAuth через админку - появляется вот [это](https://www.dropbox.com/s/3v0lmt4hbf9j125/moodle2.PNG?dl=0)
Если устанавливать по инструкции по FTP - появляется вот [это](https://www.dropbox.com/s/3k16vxppc853emz/moodle4.PNG?dl=0)
Что я делаю не так?

**Comment by tigusigalpa** [comment]
Вы все делаете верно, при установке любого нового плагина появляется экран с новыми плагинами, кнопка Обновить Moodle проинсталлирует их
