### ISSUE TITLE
заблокированный пользователь

### ISSUE THREAD

**Issue by V-Zemlyakov** [tigusigalpa/moodle-auth_lenauth#12]
если пользователь заблокирован в moodle, все рано он может войти через плагин.

**Comment by tigusigalpa** [comment]
Спасибо огромное! Сделаю фикс на этой неделе

**Comment by V-Zemlyakov** [comment]
спасибо, еще бы сделать невозможность авто регистрации нового пользователя (разрешить только вход) или обязательное подтверждение нового пользователя администратором.

**Comment by iligzar** [comment]
Если взять кусок кода из другого плангина авторизации можно реализовать:

- Обязательное подтверждение пользователя Админом, иначе он не может войти
- Отправку письма Администратору о новом пользователе, для оперативности
- Отправку письма пользователю на email, если его одобрили

**Comment by tigusigalpa** [comment]
Коллеги, добрый день! извиняюсь, не всегда хватает времени своевременно вносить правки, идеи есть, но времени нет... Ваши звездочки к плагину на github помогут, дело нехитрое. На майских обязательно все посмотрю. Пока если заинтересует блок вывода новостей из WordPress: https://github.com/tigusigalpa/moodle-block_wpfeed

**Comment by tigusigalpa** [comment]
Сделал проверку на заблокированного пользователя, спасибо! По поводу подтверждений - будет другой плагин авторизации с функциями LenAuth, там будет куда больше функционала, но он будет платным..
