### ISSUE TITLE
Multiple Google accounts - correct Google Account not used

### ISSUE THREAD

**Issue by mjsamberg** [tigusigalpa/moodle-auth_lenauth#5]
Workflow sequence:
Sign in to Google with multiple accounts (A and B)
Sign in to Moodle using Length with account A
Sign out of Moodle
Sign into Moodle using account B

Expected Result: Moodle user is account B
Actual Result: Moodle user is account A

**Comment by tigusigalpa** [comment]
Hi, Mark! thanks again for pull request and issue! will be done due 1-2 weeks!

**Comment by tigusigalpa** [comment]
Hi, Mark! Solved)
