### ISSUE TITLE
Отсутствие почты у пользователя VK

### ISSUE THREAD

**Issue by ziglik2** [tigusigalpa/moodle-auth_lenauth#6]
Отсутствие почты у пользователя VK не дает пользоваться системой. Как решать проблему? Надеюсь пишу туда, куда надо)

**Comment by tigusigalpa** [comment]
Все верно, у пользователя VK может отсутствовать почта, в этом случае скрипт ищет его Social ID (вдруг=)
Пользователь при первом входе будет обязан заполнить свой e-mail
